films/urls.py
from django.conf.urls import url
from . import views


app_name = 'films'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<film_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^edit/(?P<film_id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^download/(?P<film_id>[0-9]+)/$', views.download_film, name='download'),
]

media/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('films.urls')),
    url(r'^tvshows/', include('tvshows.urls')),
    url(r'^cron_jobs/', include('cron_jobs.urls')),
]

tvshows/urls.py
from django.conf.urls import url
from . import views


app_name = 'tvshows'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<show_id>[0-9]+)/$', views.show_detail, name='show_detail'),
    url(r'^(?P<show_id>[0-9]+)/season/(?P<season_id>[0-9]+)/$', views.season_detail, name='season_detail'),
]

tvshows/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from films.models import Genre


class Show(models.Model):
    title = models.CharField(max_length=250)
    genre = models.ForeignKey(Genre, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Season(models.Model):
    title = models.CharField(max_length=250)
    show = models.ForeignKey(Show)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Episode(models.Model):
    title = models.CharField(max_length=250)
    season = models.ForeignKey(Season)
    file_name = models.CharField(max_length=250, unique=True)
    file_extension = models.CharField(max_length=10)
    file_size = models.CharField(null=True, max_length=10)
    poster = models.CharField(null=True, max_length=250)
    background = models.CharField(null=True, max_length=250)
    first_air_date = models.DateField(null=True, auto_now=False)
    movie_db_id = models.IntegerField(null=True, default=0)
    is_viewed = models.BooleanField(default=False)
    is_updated = models.BooleanField(default=False)
    overview = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

tvshows/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from .models import Show
from django.http import JsonResponse


def index(request):
    return JsonResponse({
        'success': True
    })


def show_detail(request, show_id):
    return JsonResponse({
        'success': True
    })


def season_detail(request, show_id, season_id):
    return JsonResponse({
        'success': True
    })

tvshows/templates/shows/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Media{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy" />
    <link rel="stylesheet" type="text/css" href="{% static 'shows/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'shows/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'films:index' %}">Media</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block films_active %}{% endblock %}"><a href="{% url 'films:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Films</a></li>
                <li class="{% block shows_active %}{% endblock %}"><a href="{% url 'tvshows:index' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; TV shows</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'tvshows:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

tvshows/templates/shows/detail.html
{% extends 'shows/base.html' %}
{% block shows_active %}active{% endblock %}
{% block title %}{{ show }}{% endblock %}
{% block body %}
<div class="fims-container container-fluid">
    <div class="row">
        <!-- Left column -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-info">
                <div class="panel-body">
                    <img src="{{ poster_domain }}{{ show.poster }}" class="img-responsive" alt="Responsive image">
                    <h1>{{ show.title }}</h1>
                    <ul class="nav nav-pills" style="margin-bottom: 10px;">
                        <li role="presentation" class="active"><a href="{% url 'show:detail' show.id %}">View</a></li>
                        <li role="presentation"><a href="{% url 'show:detail' film.id %}">Edit</a></li>
                    </ul>
                </div>
            </div>
        </div>
        
        <!-- Right column -->
        <div class="col-sm-4 col-md-5">
            <div class="panel panel-info">
                <div class="panel-body">
                    <h3>TVShow datail info</h3>
                    <table class="table">
                        <tr>
                            <td class="float-right">Genre: </td>
                            <td class="float-right">{{ show.genre }}</td>
                        </tr>
                        <tr>
                            <td class="float-right">Date: </td>
                            <td class="float-right">{{ show.first_air_date }}</td>
                        </tr>
                        <tr>
                            <td class="float-right">Overview: </td>
                            <td class="float-right">{{ show.overview }}</td>
                        </tr>
                        <tr>
                            <td class="float-right">File name: </td>
                            <td class="float-right">{{ show.file_name }}</td>
                        </tr>
                        <tr>
                            <td class="float-right">File size: </td>
                            <td class="float-right">{{ show.file_size }}</td>
                        </tr>
                    </table>
                    <a href="{% url 'show:download' show.id %}" target="_blank" class="btn btn-danger btn-sm" role="button">Download</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tvshows/templates/shows/index.html
{% extends 'films/base.html' %}
{% block films_active %}active{% endblock %}
{% block title %}Films list{% endblock %}
{% block body %}
<div class="fims-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>TV shows</h3>
        </div>
        {% if films %}
            {% for film in films %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'films:detail' film.id %}">
                            {% if film.poster %}
                                <img src="{{ poster_domain }}{{ film.poster }}" class="img-responsive">
                            {% else %}
                                <img src="{{ no_image }}" class="img-responsive">
                            {% endif %}
                        </a>
                        <div class="caption">
                            <h3>{{ film.title }}</h3>
                            <h5>{{ film.genre }}</h5>

                            <!-- View Details -->
                            <a href="{% url 'films:detail' film.id %}" class="btn btn-primary btn-sm" role="button">View Detail</a>
                            <a href="{% url 'films:detail' film.id %}" class="btn btn-danger btn-sm" role="button">Edit</a>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
            </div>
        {% endif %}
    </div>

</div>
{% endblock %}