films/urls.py
from django.conf.urls import url
from . import views


app_name = 'films'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<film_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^edit/(?P<film_id>[0-9]+)/$', views.edit, name='edit'),
    url(r'^download/(?P<film_id>[0-9]+)/$', views.download_film, name='download'),
]

media/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('films.urls')),
    url(r'^tvshows/', include('tvshows.urls')),
    url(r'^cron_jobs/', include('cron_jobs.urls')),
]

films/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class Genre(models.Model):
    title = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Film(models.Model):
    title = models.CharField(max_length=250)
    genre = models.ForeignKey(Genre, default=1)
    file_name = models.CharField(max_length=250, unique=True)
    file_extension = models.CharField(max_length=10)
    file_size = models.CharField(null=True, max_length=10)
    poster = models.CharField(null=True, max_length=250)
    background = models.CharField(null=True, max_length=250)
    first_air_date = models.DateField(null=True, auto_now=False)
    movie_db_id = models.IntegerField(null=True, default=0)
    is_viewed = models.BooleanField(default=False)
    is_updated = models.BooleanField(default=False)
    overview = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

films/forms.py
from django import forms
from .models import Film


class FilmForm(forms.ModelForm):

    class Meta:
        model = Film
        fields = ['title', 'genre', 'file_name', 'is_viewed', 'is_updated']

films/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, get_object_or_404
from .models import Film
from django.conf import settings
from django.utils.encoding import smart_str
from django.http import HttpResponse
from django.core.paginator import Paginator


def index(request):
    films_list = Film.objects.all().order_by('-created_at')
    poster_domain = settings.MOVIEDB_IMAGE_PATH + settings.MOVIEDB_POSTER_SIZE

    paginator = Paginator(films_list, settings.LIST_LIMIT)
    if request.GET.get('page'):
        page = request.GET.get('page')
    else:
        page = 1
    films = paginator.page(page)
    r = range(1, films.paginator.num_pages+1)

    return render(
        request,
        'films/index.html',
        {
            'films': films,
            'range': r,
            'poster_domain': poster_domain,
            'no_image': settings.NO_IMAGE_FAKE
        }
    )


def detail(request, film_id):
    film = get_object_or_404(Film, pk=film_id)
    poster_domain = settings.MOVIEDB_IMAGE_PATH + settings.MOVIEDB_POSTER_SIZE
    background_domain = settings.MOVIEDB_IMAGE_PATH + settings.MOVIEDB_BACKGROUND_SIZE
    return render(
        request,
        'films/detail.html',
        {
            'film': film,
            'poster_domain': poster_domain,
            'background_domain': background_domain,
        })


def edit(request, film_id):
    film = get_object_or_404(Film, pk=film_id)


def download_film(request, film_id):
    film = Film.objects.get(pk=film_id)
    path_to_file = settings.FILMS_ROOT + film.file_name

    response = HttpResponse(content_type='application/force-download')
    response['Content-Disposition'] = 'attachment; filename=%s' % smart_str(film.file_name)
    response['X-Sendfile'] = path_to_file + smart_str(film.file_name)
    return response

films/templates/films/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Media{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Satisfy" />
    <link rel="stylesheet" type="text/css" href="{% static 'films/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>

    <script src="{% static 'films/js/main.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'films:index' %}">Media</a>
        </div>

        <!-- Items -->
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block films_active %}{% endblock %}"><a href="{% url 'films:index' %}"><span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp; Films</a></li>
                <li class="{% block songs_active %}{% endblock %}"><a href="{% url 'films:index' %}"><span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp; TV shows</a></li>
            </ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'films:index' %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Album
                    </a>
                </li>
                <li>
                    <a href="#">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

films/templates/films/detail.html
{% extends 'films/base.html' %}
{% block films_active %}active{% endblock %}
{% block title %}{{ film }}{% endblock %}
{% block body %}
<div class="fims-container container-fluid">
    <div class="row">
        <!-- Left column -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-info">
                <div class="panel-body">
                    <img src="{{ poster_domain }}{{ film.poster }}" class="img-responsive" alt="Responsive image">
                    <h1>{{ film.title }}</h1>
                    <ul class="nav nav-pills" style="margin-bottom: 10px;">
                        <li role="presentation" class="active"><a href="{% url 'films:detail' film.id %}">View</a></li>
                        <li role="presentation"><a href="{% url 'films:edit' film.id %}">Edit</a></li>
                    </ul>
                </div>
            </div>
        </div>
        
        <!-- Right column -->
        <div class="col-sm-4 col-md-5">
            <div class="panel panel-info">
                <div class="panel-body">
                    <h3>Movie datail info</h3>
                    <table class="table">
                        <tr>
                            <td class="float-right">Genre: </td>
                            <td class="float-right">{{ film.genre }}</td>
                        </tr>
                        <tr>
                            <td class="float-right">Date: </td>
                            <td class="float-right">{{ film.first_air_date }}</td>
                        </tr>
                        <tr>
                            <td class="float-right">Overview: </td>
                            <td class="float-right">{{ film.overview }}</td>
                        </tr>
                        <tr>
                            <td class="float-right">File name: </td>
                            <td class="float-right">{{ film.file_name }}</td>
                        </tr>
                        <tr>
                            <td class="float-right">File size: </td>
                            <td class="float-right">{{ film.file_size }}</td>
                        </tr>
                    </table>
                    <a href="{% url 'films:download' film.id %}" target="_blank" class="btn btn-danger btn-sm" role="button">Download</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

films/templates/films/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

films/templates/films/index.html
{% extends 'films/base.html' %}
{% block films_active %}active{% endblock %}
{% block title %}Films list{% endblock %}
{% block body %}
<div class="fims-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Films</h3>
        </div>
        {% if films %}
            {% for film in films %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'films:detail' film.id %}">
                            {% if film.poster %}
                                <img src="{{ poster_domain }}{{ film.poster }}" class="img-responsive">
                            {% else %}
                                <img src="{{ no_image }}" class="img-responsive">
                            {% endif %}
                        </a>
                        <div class="caption">
                            <h3>{{ film.title }}</h3>
                            <h5>{{ film.genre }}</h5>

                            <!-- View Details -->
                            <a href="{% url 'films:detail' film.id %}" class="btn btn-primary btn-sm" role="button">View Detail</a>
                            <a href="{% url 'films:detail' film.id %}" class="btn btn-danger btn-sm" role="button">Edit</a>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
            <div class="col-sm-12">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        {% if films.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page=1">&laquo; First</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ films.previous_page_number }}">Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">&laquo; First</a>
                            </li>
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                        {% endif %}

                        {% for i in range %}
                            <li class="page-item{% if i == films.number %} active{% endif %}">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endfor %}

                        {% if films.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ films.next_page_number }}">Next</a>
                            </li>
                            <li class="page-item">
                                <a class="page-link" href="?page={{ films.paginator.num_pages }}">Last &raquo;</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Next</a>
                            </li>
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Last &raquo;</a>
                            </li>
                        {% endif %}
                    </ul>
                </nav>
            </div>
        {% else %}
            <div class="col-sm-12">
                <br>
            </div>
        {% endif %}
    </div>

</div>
{% endblock %}